config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/new'

  root 'ontap#index'
  
  get 'sessions/new'
  get 'users/new'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users
  
  resources :index do
    resources :beers
  end
  resources :users do
    resources :beers
  end
  
  resources :beers do
    resources :comments
  end

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  #attr_accessible :name, :tasting_notes, :brewery, :user_id
  belongs_to :user
  has_many :comments, dependent: :destroy
  #default_scope -> {order(created_at: :asc)}
  validates :brewery, presence: true, length: {minimum: 3}
  validates :name, presence: true, length: {minimum: 3}
  validates :tasting_notes, presence: true, length: {minimum: 3}
  validates :user_id, presence: true                   
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :beer
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :beers, dependent: :destroy
  has_many :comments, through: :beers
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  #attr_accessible :name, :email, :password, :password_confirmation
  validates :name, presence: true, length: { maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255},
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token for remembering sessions
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers user in database for persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if given token matches the digest
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forget user
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  
  def index
    #@beers = Beer.all
    @beers = Beer.order(params[:sort])
  end

  def show
    @beer = Beer.find(params[:id])
  end
   
  def new
    @beer = Beer.new
  end
  
  def create
    @beer = current_user.beers.build(beer_params)
  
    if @beer.save
      redirect_to @beer
    else
      render 'new'
    end
  end
  
  def edit
    @beer = Beer.find(params[:id])
  end
  
  def update
    @beer = Beer.find(params[:id])
    
    if @beer.update(beer_params)
      redirect_to @beer
    else
      render 'edit'
    end
  end
  
  def destroy
    @beer = Beer.find(params[:id])
    @beer.destroy
    
    redirect_to beers_path
  end
  
  private
    def beer_params
      params.require(:beer).permit(:brewery, :name, :tasting_notes)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "Mr_S", password: "homebrew", only: :destroy
  
  def create
    @beer = Beer.find(params[:beer_id])
    @comment = @beer.comments.create(comment_params)
    redirect_to beer_path(@beer)
  end
  
  def destroy
    @beer = Beer.find(params[:beer_id])
    @comment = @beer.comments.find(params[:id])
    @comment.destroy
    redirect_to beer_path(@beer)
  end
  
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/ontap_controller.rb
class OntapController < ApplicationController
  helper_method :sort_column, :sort_direction  
  
  def index
    @beers = Beer.order(sort_column + " " + sort_direction)
    #@beers = Beer.order(params[:sort])
  end
  
  private
  
  def sort_column
    Beer.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the User in and redirect to user's show page
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      # Create error message
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params) # Not the final implementation!
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Beermon! Start Tasting 'Em All!"
      redirect_to @user
      # Handle a successful save.
    else
      render "new"
    end
  end
  
  def show
    @user = User.find(params[:id])
    @beers = @user.beers.paginate(page: params[:page], :per_page => 5)
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title=nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction} , {:class => css_class}
  end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ontap_helper.rb
module OntapHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in persistent session
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  # Returns the current logged-in user (if any). 
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
 
  # Returns true if the user is logged in, false otherwise. 
  def logged_in?
    !current_user.nil?
  end
  
  #Forget persistent session
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  # Log out current user
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  
end

app/helpers/users_helper.rb
module UsersHelper
  
  #Return Gravatar for the given user
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/beers/_beer.html.erb
<br>
<li id="beer" >
  <%= link_to gravatar_for(beer.user), beer_path(beer) %>
  <span class="brewery"><%= beer.brewery.upcase %>: <%= beer.name %></span>
  <span class="tasting_notes"><%= beer.tasting_notes %></span>
  <span class="timestamp">
    Tasted <%= time_ago_in_words(beer.created_at) %> ago. 
  </span>
</li>
  
  

app/views/beers/_form.html.erb
<%= form_for @beer do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
   	  <h2>
   	  	<%= pluralize(@beer.errors.count, "error")%> Could not save this beer you tasted:
   	  </h2>
   	  <ul>
   	  	<% @beer.errors.full_messages.each do |msg| %>
   	  	  <li><%= msg %></li>
   	  	<% end %>
   	  </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">  
  <p>
  	<%= f.label :brewery %><br>
  	<%= f.text_field :brewery, class: 'form-control' %>
  </p>
  
  <p>
  	<%= f.label :name %><br>
  	<%= f.text_field :name, class: 'form-control' %>
  </p>

  <p>
  	<%= f.label :tasting_notes %><br>
  	<%= f.text_area :tasting_notes, class: 'form-control' %>
  </p>
  </div>
</div>
  <p>
  	<div class="btn-group btn-block" id="logsign">
      <%= f.submit "Add This Beer", class: "btn btn-primary" %>
      <%= link_to "Haven't Tasted It", user_path(current_user), class: "btn btn-primary" %>
    </div>
  </p>
<% end%>

app/views/beers/edit.html.erb
<h1>Retasting Beer</h1>

<%= render 'form' %>

<div class="logtaste">
  <%= link_to "I don't want to update this beer", user_path(current_user)%>
</div>

app/views/beers/index.html.erb
<h1>Beers You've Tasted</h1>
<%= link_to 'Taste a Beer', new_beer_path %>
<table>
  <tr>
	<th>Brewery</th>
	<th>Beer</th>
	<th>Tasting Notes</th>
  </tr>
  
  <% @beers.each do |beer| %>
    <tr>
    	<td><%= beer.brewery %></td>
    	<td><%= beer.name %></td>
    	<td><%= beer.tasting_notes %></td>
    	<td><%= link_to 'Show', beer_path(beer) %></td>
    	<td><%= link_to 'Edit', edit_beer_path(beer) %></td>
    	<td><%= link_to 'Destroy', beer_path(beer), method: :delete, data: {confirm: 'Are You Sure?'} %></td>
    </tr>
    
  <% end %>

</table>

app/views/beers/new.html.erb
<h1>What Beer Did you Taste?</h1>

<%= render 'form' %>

<div class="logtaste">
  <%= link_to "I haven't finished my beer", user_path(current_user)%>
</div>

app/views/beers/show.html.erb
<h1>You've Tasted <%= @beer.name %></h1>
<p>
  <strong>Brewed By:</strong>
  <%= @beer.brewery%>
</p>

<p>
  <strong>Tasting Notes:</strong>
  <%= @beer.tasting_notes%>
</p>

<!--Begin Comment Section-->
<h3>Beerments</h3>
<%= render @beer.comments%>

<h3>Add a comment about the beer</h3>
<%= render 'comments/form' %>
<!--End Comment Section-->

app/views/comments/_comment.html.erb
  <p>
  	<strong>Commenter:</strong>
  	<%= comment.commenter %>
  </p>

  <p>
  	<strong>Beerment:</strong>
  	<%= comment.body %>
  </p>
  
  <p>
  	<%= link_to 'Destroy Comment', [comment.beer, comment],
  	             method: :delete,
  	             data: { confirm: 'Are you sure?' } %>
  </p>

app/views/comments/_form.html.erb
<%= form_for ([@beer, @beer.comments.build]) do |f| %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
  <p>
  	<%= f.label :commenter %> <br>
  	<%= f.text_field :commenter, class: 'form-control' %>
  </p>  
  <p>
  	<%= f.label :beerment %><br>
	<%= f.text_area :body, class: 'form-control' %>
  </p>
  </div>
</div>  
  <div class= "logtaste">
  	<%= f.submit "Join The Discussion", class: "btn btn-primary" %>
    <p class="editsee">
      <%= link_to "I want to edit the beer I just tasted", edit_beer_path(@beer) %> |
      <%= link_to "I want to see the other beers I've Tasted", user_path(current_user) %>
    </p>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Beermon", root_path, id: "logo", style: "float:right" %>
  <% if logged_in? %>
    <%= link_to "User", user_path(current_user), class: "btn-sm btn-primary" %>
    <%= link_to "LOG OUT", logout_path, class: "btn-sm btn-primary", method: "delete" %>
  <% else %>
    <%= link_to "SIGN UP HERE", signup_path, class: "btn-sm btn-primary" %>
    <%= link_to "LOG IN", login_path, class: "btn-sm btn-primary" %>     
  <% end %>
  <p style= "float:right; margin-left:5px;">BEERMON</p>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beermon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id = "user_header">
  <!-- link_to "Sign Up", users_new_path -->
  
  <% if logged_in? %>
    <%= link_to current_user.name.upcase, user_path(current_user), class: "btn-sm btn-primary" %>
    <%= link_to "LOG OUT", logout_path, class: "btn-sm btn-primary", method: "delete" %>
  <% else %>
    <%= link_to "SIGN UP HERE", signup_path, class: "btn-sm btn-primary" %>
    <%= link_to "LOG IN", login_path, class: "btn-sm btn-primary" %>     
  <% end %>
  <%= link_to "BEERMON", root_path, id: "logo", class: "home" %>
  <!--<p style= "float:right; margin-left:5px;">BEERMON</p>-->
</div>
<div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/ontap/index.html.erb
<h1 id="gotta">Beermon: Gotta Taste em all!</h1>
<!--<%#= link_to 'Beers Tasted', controller: 'beers' %>-->
  
<table class="table table-striped">
  <tr>
	<th><%= sortable "brewery" %></th>
	<th><%= sortable "name", "Beer" %></th>
	<th><%= sortable "tasting_notes" %></th>
  </tr>
  
  <% @beers.each do |beer| %>
    <tr>
    	<td><%= beer.brewery %></td>
    	<td><%= beer.name %></td>
    	<td><%= beer.tasting_notes %></td>
    </tr>
  <% end %>
</table>


<div class="btn-group btn-block" id="logsign">
  <%= link_to "Log In", login_path, class: "btn btn-primary" %>
  <%= link_to "Sign Up Here", signup_path, class: "btn btn-primary" %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
  	<div class="alert alert-danger">
  	  The form contains <%= pluralize(@user.errors.count, "error") %>
  	</div>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render 'shared/error_messages' %>

  <p>
  	<%= f.label :name %><br>
  	<%= f.text_field :name, class: 'form-control' %>
  </p>
  
  <p>
  	<%= f.label :email %><br>
  	<%= f.email_field :email, class: 'form-control' %>
  </p>
  
  <p>
  	<%= f.label :password %><br>
  	<%= f.password_field :password, class: 'form-control' %>
  </p>
  
  <p>
  	<%= f.label :password_confirmation, "Password Confirmation" %><br>
  	<%= f.password_field :password_confirmation, class: 'form-control'  %>
  </p>
  
  <div class="logtaste">
  	<%= f.submit "Start Tasting Beer", class: 'btn btn-primary'%>
    <p><%= link_to "I don't want to sign up", root_path %></p>
  </div>
<% end%>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="user_name">
  <h1><%= gravatar_for @user %></h1>
  <h1><%= @user.name.upcase%></h1>
</div>

<div class="col-md-12">
  <% if @user.beers.any? %>
    <h3>You've Tasted <%= @user.beers.count %> Beers!</h3>
    <ol class="beers">
 	  <%= render @beers %>
    </ol>
    <%= will_paginate @beers %>
  <% end %>
</div>
<div class="tastebeer">
  <%= link_to 'Taste a Beer', new_beer_path, class: "btn btn-primary btn-block"%>
</div>
 <%= yield :beers %>
 